// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > web/types/database.ts
// after starting local Supabase with: supabase start

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          user_id: string
          display_name: string
          avatar_url: string | null
          bio: string | null
          minecraft_java_username: string | null
          minecraft_bedrock_gamertag: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          user_id: string
          display_name: string
          avatar_url?: string | null
          bio?: string | null
          minecraft_java_username?: string | null
          minecraft_bedrock_gamertag?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          display_name?: string
          avatar_url?: string | null
          bio?: string | null
          minecraft_java_username?: string | null
          minecraft_bedrock_gamertag?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      worlds: {
        Row: {
          id: string
          name: string
          description: string | null
          how_to_join: string | null
          icon_url: string | null
          owner_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          how_to_join?: string | null
          icon_url?: string | null
          owner_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          how_to_join?: string | null
          icon_url?: string | null
          owner_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'worlds_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      world_members: {
        Row: {
          id: string
          world_id: string
          user_id: string
          joined_at: string
        }
        Insert: {
          id?: string
          world_id: string
          user_id: string
          joined_at?: string
        }
        Update: {
          id?: string
          world_id?: string
          user_id?: string
          joined_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'world_members_world_id_fkey'
            columns: ['world_id']
            isOneToOne: false
            referencedRelation: 'worlds'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'world_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      posts: {
        Row: {
          id: string
          user_id: string
          world_id: string | null
          content: string
          visibility: 'public' | 'world_only'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          world_id?: string | null
          content: string
          visibility?: 'public' | 'world_only'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          world_id?: string | null
          content?: string
          visibility?: 'public' | 'world_only'
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'posts_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'posts_world_id_fkey'
            columns: ['world_id']
            isOneToOne: false
            referencedRelation: 'worlds'
            referencedColumns: ['id']
          }
        ]
      }
      post_images: {
        Row: {
          id: string
          post_id: string
          image_url: string
          display_order: number
        }
        Insert: {
          id?: string
          post_id: string
          image_url: string
          display_order: number
        }
        Update: {
          id?: string
          post_id?: string
          image_url?: string
          display_order?: number
        }
        Relationships: [
          {
            foreignKeyName: 'post_images_post_id_fkey'
            columns: ['post_id']
            isOneToOne: false
            referencedRelation: 'posts'
            referencedColumns: ['id']
          }
        ]
      }
      likes: {
        Row: {
          id: string
          user_id: string
          post_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          post_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          post_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'likes_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'likes_post_id_fkey'
            columns: ['post_id']
            isOneToOne: false
            referencedRelation: 'posts'
            referencedColumns: ['id']
          }
        ]
      }
      comments: {
        Row: {
          id: string
          user_id: string
          post_id: string
          parent_comment_id: string | null
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          post_id: string
          parent_comment_id?: string | null
          content: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          post_id?: string
          parent_comment_id?: string | null
          content?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'comments_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'comments_post_id_fkey'
            columns: ['post_id']
            isOneToOne: false
            referencedRelation: 'posts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'comments_parent_comment_id_fkey'
            columns: ['parent_comment_id']
            isOneToOne: false
            referencedRelation: 'comments'
            referencedColumns: ['id']
          }
        ]
      }
      comment_likes: {
        Row: {
          id: string
          user_id: string
          comment_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          comment_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          comment_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'comment_likes_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'comment_likes_comment_id_fkey'
            columns: ['comment_id']
            isOneToOne: false
            referencedRelation: 'comments'
            referencedColumns: ['id']
          }
        ]
      }
      reposts: {
        Row: {
          id: string
          user_id: string
          post_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          post_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          post_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'reposts_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'reposts_post_id_fkey'
            columns: ['post_id']
            isOneToOne: false
            referencedRelation: 'posts'
            referencedColumns: ['id']
          }
        ]
      }
      follows: {
        Row: {
          id: string
          follower_id: string
          following_id: string
          created_at: string
        }
        Insert: {
          id?: string
          follower_id: string
          following_id: string
          created_at?: string
        }
        Update: {
          id?: string
          follower_id?: string
          following_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'follows_follower_id_fkey'
            columns: ['follower_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'follows_following_id_fkey'
            columns: ['following_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'like' | 'comment' | 'follow' | 'repost' | 'comment_like'
          actor_id: string
          post_id: string | null
          comment_id: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'like' | 'comment' | 'follow' | 'repost' | 'comment_like'
          actor_id: string
          post_id?: string | null
          comment_id?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'like' | 'comment' | 'follow' | 'repost' | 'comment_like'
          actor_id?: string
          post_id?: string | null
          comment_id?: string | null
          is_read?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_post_id_fkey'
            columns: ['post_id']
            isOneToOne: false
            referencedRelation: 'posts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notifications_comment_id_fkey'
            columns: ['comment_id']
            isOneToOne: false
            referencedRelation: 'comments'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_feed_latest: {
        Args: {
          p_limit?: number
          p_cursor?: string
        }
        Returns: {
          id: string
          user_id: string
          world_id: string | null
          content: string
          visibility: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          world_name: string | null
          world_icon_url: string | null
          likes_count: number
          comments_count: number
          reposts_count: number
          images: Json
        }[]
      }
      get_feed_recommended: {
        Args: {
          p_limit?: number
          p_offset?: number
        }
        Returns: {
          id: string
          user_id: string
          world_id: string | null
          content: string
          visibility: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          world_name: string | null
          world_icon_url: string | null
          likes_count: number
          comments_count: number
          reposts_count: number
          images: Json
          score: number
        }[]
      }
      get_feed_following: {
        Args: {
          p_user_id: string
          p_limit?: number
          p_cursor?: string
        }
        Returns: {
          id: string
          user_id: string
          world_id: string | null
          content: string
          visibility: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          world_name: string | null
          world_icon_url: string | null
          likes_count: number
          comments_count: number
          reposts_count: number
          images: Json
        }[]
      }
      get_feed_world: {
        Args: {
          p_world_id: string
          p_limit?: number
          p_cursor?: string
        }
        Returns: {
          id: string
          user_id: string
          world_id: string
          content: string
          visibility: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          likes_count: number
          comments_count: number
          reposts_count: number
          images: Json
        }[]
      }
      get_post_with_details: {
        Args: {
          p_post_id: string
        }
        Returns: {
          id: string
          user_id: string
          world_id: string | null
          content: string
          visibility: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          world_name: string | null
          world_icon_url: string | null
          likes_count: number
          comments_count: number
          reposts_count: number
          images: Json
        }[]
      }
      get_comments_tree: {
        Args: {
          p_post_id: string
        }
        Returns: {
          id: string
          user_id: string
          post_id: string
          parent_comment_id: string | null
          content: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          likes_count: number
          depth: number
        }[]
      }
      search_users: {
        Args: {
          p_query: string
          p_limit?: number
        }
        Returns: {
          id: string
          user_id: string
          display_name: string
          avatar_url: string | null
          bio: string | null
          followers_count: number
          following_count: number
        }[]
      }
      search_worlds: {
        Args: {
          p_query: string
          p_limit?: number
        }
        Returns: {
          id: string
          name: string
          description: string | null
          icon_url: string | null
          owner_id: string
          owner_display_name: string
          owner_user_id: string
          members_count: number
        }[]
      }
      search_posts: {
        Args: {
          p_query: string
          p_limit?: number
        }
        Returns: {
          id: string
          user_id: string
          world_id: string | null
          content: string
          visibility: string
          created_at: string
          user_display_name: string
          user_user_id: string
          user_avatar_url: string | null
          world_name: string | null
          likes_count: number
          comments_count: number
          reposts_count: number
          images: Json
        }[]
      }
      get_user_stats: {
        Args: {
          p_user_id: string
        }
        Returns: {
          posts_count: number
          followers_count: number
          following_count: number
          worlds_count: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
export type Functions<T extends keyof Database['public']['Functions']> =
  Database['public']['Functions'][T]
